name: Build dotnet-runtime

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Repo name env
      run: echo "REPO_NAME=dotnet-runtime" >> $GITHUB_ENV

    - name: Set dotnet channel env
      run: echo "DOTNET_CHANNEL=Current" >> $GITHUB_ENV

    - name: Set dotnet version env
      run: echo "DOTNET_VERSION=$(wget -qO - https://dotnetcli.azureedge.net/dotnet/Runtime/$DOTNET_CHANNEL/latest.version)" >> $GITHUB_ENV

    - name: Log repository name and dotnet version
      run: echo "Building $REPO_NAME with dotnet version $DOTNET_VERSION"

    - uses: actions/checkout@v2
    - name: Build ${{ env.REPO_NAME }} with dotnet ${{ env.DOTNET_CHANNEL }} version ${{ env.DOTNET_VERSION }}
      run: docker build . --file ${{ env.REPO_NAME }}/Dockerfile --build-arg dotnet_channel=${{ env.DOTNET_CHANNEL }} --build-arg dotnet_version=${{ env.DOTNET_VERSION }} --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.DOTNET_CHANNEL }}-$(date +%s)

    - name: Set dotnet channel env
      run: echo "DOTNET_CHANNEL=LTS" >> $GITHUB_ENV

    - name: Set dotnet version env
      run: echo "DOTNET_VERSION=$(wget -qO - https://dotnetcli.azureedge.net/dotnet/Runtime/$DOTNET_CHANNEL/latest.version)" >> $GITHUB_ENV

    - name: Log repository name and dotnet version
      run: echo "Building $REPO_NAME with dotnet version $DOTNET_VERSION"

    - uses: actions/checkout@v2
    - name: Build ${{ env.REPO_NAME }} with dotnet ${{ env.DOTNET_CHANNEL }} version ${{ env.DOTNET_VERSION }}
      run: docker build . --file ${{ env.REPO_NAME }}/Dockerfile --build-arg dotnet_channel=${{ env.DOTNET_CHANNEL }} --build-arg dotnet_version=${{ env.DOTNET_VERSION }} --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.DOTNET_CHANNEL }}-$(date +%s)
