name: Docker Images CI

on:
  schedule:
  - cron: "0 4 * * 0-6"
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#    - name: Build the Docker images
#      run: ./build.sh
    - name: Set env
      run: echo "DOTNET_VERSION=$(wget -qO - https://dotnetcli.azureedge.net/dotnet/Runtime/LTS/latest.version)" >> $GITHUB_ENV
    - name: Test
      run: echo $DOTNET_VERSION
#    - name: Push docker images
#      uses: docker/build-push-action@v2
