name: Docker Images CI

on:
  schedule:
  - cron: "0 4 * * 0-6"
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: build.sh
