name: Deploy dotnet-build Current

on:
  schedule:
  - cron: "0 4 * * 0-6"
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set Repo name env
      run: echo "REPO_NAME=dotnet-build" >> $GITHUB_ENV

    - name: Set dotnet version env
      run: echo "DOTNET_VERSION=$(wget -qO - https://dotnetcli.azureedge.net/dotnet/Runtime/Current/latest.version)" >> $GITHUB_ENV

    - name: Log repository name and dotnet version
      run: echo "Building $REPO_NAME with dotnet version $DOTNET_VERSION"

    - name: Build and push ${{ env.REPO_NAME }}
      uses: docker/build-push-action@v2.9.0
      with:
        # List of build-time variables
        build-args: dotnet_version="--version ${{ env.DOTNET_VERSION }}"
        # Path to the Dockerfile
        file: ./${{ env.REPO_NAME }}/Dockerfile
        # List of tags
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.DOTNET_VERSION }}, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest
